name: deploy-to-eb

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build client
        run: cd client && npm install --no-audit && npm run build

      - name: build server
        run: npm install --no-audit

      - name: Create dist folder
        run: ./dist.sh

      - name: Create ZIP deployment package
        run: cd dist && zip -r ../deploy_package.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"


      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://queenb-deploy-bucket/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name queenb-shahar \
          --source-bundle S3Bucket="queenb-deploy-bucket",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Queenb-shahar-env  --version-label "ver-${{ github.sha }}"
